# Required metadata
sonar.projectKey=mybandnow-api
sonar.projectName=Mybandnow API
sonar.projectVersion=${env.SONAR_PROJECT_VERSION}

# Comma-separated paths to directories with sources (required)
sonar.sources=src
sonar.exclusions=node_modules/**, logs/**, database/**, wiki/**, test/**, dist/**, build-tools/**

# Language
sonar.language=ts

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Test coverage report
sonar.typescript.lcov.reportPaths=reports/coverage/lcov.info

# Coverage exclusions (files without testable logic)
sonar.coverage.exclusions=**/index.ts,**/start.ts,**/domain/*Bus.ts,**/domain/*Handler.ts,**/domain/*Config.ts,**/domain/Logger.ts,**/domain/Nullable.ts,**/domain/Primitives.ts,**/domain/Response.ts,**/domain/HealthChecker.ts,**/domain/JWTVerifier.ts,**/domain/Clock.ts,**/domain/Outbox.ts,**/domain/database/*.ts,**/infrastructure/**/ConnectionSettings.ts,**/infrastructure/**/ExchangeSetting.ts,**/infrastructure/**/*Config.ts,**/infrastructure/**/ConnectionManager.ts,**/middlewares/Middleware.ts
